os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8

platform:
  - x64
  - x86

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - ps: Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
  - npm config get
  # upgrade node-gyp to dodge 2013 compile issue present in the node gyp bundled with node v0.10
  # https://github.com/nodejs/node-gyp/issues/972#issuecomment-231055109
  - IF "%nodejs_version:~0,1%"=="0" npm install node-gyp@3.x
  # downgrade npm with node v6 to dodge npm 3.10.10 bug whereby --nodedir/--dist-url is not passed to node-gyp
  - IF "%nodejs_version:~0,1%"=="6" npm install npm@2.x -g
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - IF /I "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - IF /I "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - IF /I "%PLATFORM%" == "x64" CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - IF /I "%PLATFORM%" == "x86" CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - npm install
  - npm test

build: off
test: off
deploy: off
